# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
cache: packages

install:
- R -e 'install.packages("devtools")'
- R -e 'devtools::install_deps(dep = T)'

script:
- R CMD build .
- Rscript -e "devtools::install_github("ACAD-UofA/PolyLinkR"); library(PolyLinkR); library(testthat); testthat::test_dir('tests/testthat')"
